/**
 * Payment Confirmation Handler
 * Handles payment confirmation responses (Ya/Y or Tidak/T)
 */

import { pendingPaymentConfirmations } from '../state/store.js';
import { recalculateOrderPaymentSummary } from '../repos/orders.repo.js';
import { createPaymentRecord } from '../repos/payment-history.repo.js';
import { formatCurrencyIDR } from '../utils/formatting.js';

/**
 * Handle payment confirmation (Ya/Y or Tidak/T response)
 * @param {number} chatId - Telegram chat ID
 * @param {number} userId - Telegram user ID
 * @param {string} response - User response (Ya/Y/Tidak/T)
 * @param {Function} sendMessage - Function to send Telegram message
 * @returns {Promise<boolean>} True if handled, false otherwise
 */
export async function handlePaymentConfirmation(chatId, userId, response, sendMessage) {
  const responseUpper = response.toUpperCase().trim();
  // Accept both Indonesian (Ya/Tidak) and English (Y/T) for flexibility
  const isConfirm = responseUpper === 'YA' || responseUpper === 'Y';
  const isCancel = responseUpper === 'TIDAK' || responseUpper === 'T';
  
  if (!isConfirm && !isCancel) {
    return false; // Not a payment confirmation
  }

  // Find pending confirmation for this user
  let foundKey = null;
  for (const [key, data] of pendingPaymentConfirmations.entries()) {
    if (key.startsWith(`${userId}:`)) {
      foundKey = key;
      break;
    }
  }
  
  if (!foundKey) {
    return false; // No pending confirmation
  }
  
  const confirmation = pendingPaymentConfirmations.get(foundKey);
  pendingPaymentConfirmations.delete(foundKey);
  
  if (isConfirm) {
    // AUTO-APPROVE: User confirmed payment
    try {
      // Write to Payment_History with status="confirmed"
      // payment_id and payment_date are auto-generated by createPaymentRecord
      // amount_confirmed = amount_input after user confirms with "Y"
      const paymentMethod = confirmation.paymentMethod || (confirmation.source === 'manual_entry' ? 'manual' : 'transfer');
      
      // Auto-generate note based on payment method and user
      let note = '';
      if (paymentMethod === 'manual') {
        note = `Pembayaran manual entry by admin\nDikonfirmasi oleh admin (user ${userId})`;
      } else {
        note = `Dikonfirmasi oleh admin (user ${userId})`;
      }
      // If there's an existing note from confirmation, prepend it
      if (confirmation.note && confirmation.note.trim()) {
        note = `${confirmation.note}\n${note}`;
      }
      
      const paymentRecord = await createPaymentRecord({
        order_id: confirmation.orderId,
        amount_input: confirmation.amountInput,
        amount_confirmed: confirmation.amountInput, // After "Y" confirmation, amount_confirmed = amount_input
        payment_method: paymentMethod, // 'manual' for /pay command, 'transfer' for evidence upload
        status: 'confirmed',
        currency: 'IDR', // Default: IDR
        note: note, // Auto-filled: "Pembayaran manual entry by admin\nDikonfirmasi oleh admin (user XXX)"
        proof_file_id: confirmation.proofFileId || '', // Optional
        proof_caption: confirmation.proofCaption || '', // Optional
        created_by: String(userId), // Auto-filled with user_id
      });
      
      console.log(`[PAY_FLOW] Approved payment saved: payment_id=${paymentRecord.payment_id}, order_id=${confirmation.orderId}, amount_confirmed=${confirmation.amountInput}`);
      
      // Recalculate order payment summary from Payment_History
      let summary;
      try {
        summary = await recalculateOrderPaymentSummary(confirmation.orderId);
      } catch (recalcError) {
        console.error(`❌ [PAY_CONFIRM] Error recalculating payment summary:`, recalcError);
        console.error(`❌ [PAY_CONFIRM] Stack:`, recalcError.stack);
        // Payment was saved, but Orders update failed - notify user
        await sendMessage(
          chatId,
          '⚠️ **Pembayaran berhasil dicatat, tapi sistem gagal memperbarui status pesanan. Admin akan cek manual.**\n\n' +
          `📋 Order: \`${confirmation.orderId}\`\n` +
          `💵 Nominal: ${formatCurrencyIDR(confirmation.amountInput)}\n\n` +
          'Silakan hubungi admin untuk verifikasi.'
        );
        return true; // Handled, but with error
      }
      
      // Reply in Indonesian with updated totals
      let message = '✅ **Pembayaran diterima.**\n\n';
      message += `📋 Order: \`${confirmation.orderId}\`\n`;
      message += `💵 Nominal: ${formatCurrencyIDR(confirmation.amountInput)}\n`;
      message += `💰 Total terverifikasi: ${formatCurrencyIDR(summary.totalPaid)}\n`;
      message += `📊 Sisa tagihan: ${formatCurrencyIDR(summary.remainingBalance)}\n`;
      
      if (summary.paymentStatus === 'paid') {
        message += `\n✅ Status: LUNAS`;
      } else if (summary.paymentStatus === 'partial') {
        message += `\n⚠️ Status: DP PAID`;
      } else if (summary.paymentStatus === 'overpaid') {
        message += `\n✅ Status: LUNAS (Lebih Bayar)`;
      } else {
        message += `\n❌ Status: UNPAID`;
      }
      
      await sendMessage(chatId, message);
    } catch (error) {
      console.error('❌ [PAY_CONFIRM] Error confirming payment:', error);
      await sendMessage(chatId, `❌ Terjadi kesalahan: ${error.message || 'Gagal memproses pembayaran. Silakan coba lagi.'}`);
    }
  } else {
    // CANCEL: User rejected payment
    // Do NOT write to Payment_History (or write with status="rejected")
    try {
      // Option: Write rejected record for audit trail (optional)
      // For now, we'll just cancel without writing (minimal change)
      await sendMessage(
        chatId,
        '❌ **Pembayaran dibatalkan.**\n\n' +
        'Jika ingin bayar, silakan kirim ulang `/pay <ORDER_ID> <AMOUNT>`.'
      );
    } catch (error) {
      console.error('❌ [PAY_CONFIRM] Error cancelling payment:', error);
      await sendMessage(chatId, '❌ Terjadi kesalahan saat membatalkan pembayaran.');
    }
  }
  
  return true; // Handled
}
